spring:
  boot:
    admin:
      client:
        url: http://localhost:1111
msg: Hi i am from Greet Api from GIT-HUB from ankit gagare


management:
  endpoints:
    web:
      exposure:
        include: "*"
