spring:
  application:
      name: GREET-API-1
  boot:
    admin:
      client:
        url: http://localhost:1111
msg: Hi i am from Greet Api


management:
  endpoints:
    web:
      exposure:
        include: "*"
