spring:
  application:
      name: GREET-API-1
  boot:
    admin:
      client:
        url: http://localhost:1111

server:
  port: 9000



management:
  endpoints:
    web:
      exposure:
        include: "*"
